### ISSUE TITLE
birinchi page da font-weight: bold; bo'ladigan qismlar

### ISSUE THREAD

**Issue by ShokhrukhTurgunov** [vayvoo/ecomm_1106#5]
![Screenshot_2](https://user-images.githubusercontent.com/77617034/123371937-15a9dc00-d59c-11eb-9aa9-56f5774206b0.png)
![Screenshot_3](https://user-images.githubusercontent.com/77617034/123371940-16db0900-d59c-11eb-9401-8f262528c668.png)
![Screenshot_4](https://user-images.githubusercontent.com/77617034/123371945-17739f80-d59c-11eb-863d-e52943263811.png)
![Screenshot_1](https://user-images.githubusercontent.com/77617034/123371947-18a4cc80-d59c-11eb-8415-bb4eec906b12.png)

**Comment by vayvoo** [comment]
thank you. i fixed all bold issues like our design))
